language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- ! "$(cd /usr/local/bin && \\\n  sudo curl -O https://raw.githubusercontent.com/dev-op-spec/cli/master/dev-op-spec
  && \\\n  sudo chmod +x dev-op-spec)\n"
services:
- docker
script:
- bash dev-op-spec dev-ops run unit-test
- bash dev-op-spec dev-ops run set-environment
- bash dev-op-spec dev-ops run publish
env:
  global:
  - secure: jw5aZ3Hk8nFd9QetmewfGK3o0gltDZEg2pCvnocGU024BQs8He233VkeBBYr3iqGatThbmQODuqTmrvtvDSxcG5RiV3bz8H6y/hcfP76vgEfEB1QpvBGhqIMQXFMYV/bc4GRXnAfmtXgTUyBiVtBP1Zhl8MVpvQblSW46iZ5SUdDqOv6fvlS9+7kTVHsDQOI4xTxrfmYhl1yOSt1/f+M1sjtX2YFtYgoy3k4YC5lS0bhVYFgDtIEBFyV+WxWj5pHXTswDwr6Xngn/e/knZHsL5S6IxBlwHfAb2nH3qjniln0EO1Vrm5ukrdNMhj8UckmsSnwOj3r5uZiE9Wb92CawbP6RKvLktx1047C4F/UqDmZRmrfBFJmLhuKpdH/rggbe3SVZ7g9MzjPqUVOx0UBLlC96Z3s/4w+Rpto/tGpbB9mFw/BOW1TOjIIk69bDxdc/+PqMTDbBd829rVvFVNcBXnYGkGBoeP9EYVuqsSR6P9OUZJBbWICYq0N9vSGUWShXYwWR7NwWJaQF/PI6+QVkphPzpv0hqwSpn1o53hT35h6bt7CMFY/DXQwPxJfqoBcsRovG6B9yLhkzxUS8lWfe+q2i0RodkUT7sUsoS1YTftRB8Kg4ZyajVBdLA70Cj1BvlHxQzVOGI3u2N4Lri4p4VM3vmVBsRz2Uz+tmP0hSEw=
  - secure: MkjDc2QqN5J9LiTGZ1ihvP+3ZGteUEaxgk20J2gIMeb8FpQk0IwTTAJE1W5epEre/GpwE40aQbO1CyyIkYNrwYLoj5+35tmEbRKgh8n29yAZuWzOHQPIlh1CE/Om8mE2HswZkaX2ZFAVAhAvzRKG7bq/fkZphgRR+ten4QSM/viQebgBqdO25rDiNl77fXbWgaay5M7hruZL2/THi8t4LqvmtHIe3IvGgnGMA9n0qL4zBEqm7cUqJ6lannqK3CmBOe7/rbjRw+DvfrCR71oDqYoG9zPOAHwSemUqlXLBAghvP0mCcG1aBsEPlMLxNzON5jy8Uy+tEKdFwnEoEEr5Ai+l5NPfJkg4NXzWhQxQykyXEE3yeQzDcGekzZGQ46pgn/xHBCQtyAZeZ9/8S1asfCtpcBcfnJkimREdzq75qX64Qhr5NKOl3mDodHl+H4sMX33ZEfOZkLoSZpB5c0Q7DEwvK3S2FrjpVhGjTA2BXlpvrCcHrqMxrHlB6cGZWADYlyA2l+KdxBVSQSdoiqRDdn/Vdt5/UNdyKZZcAT1pXw9ZdnC8qx5HOqYlZ1awEmD6GQ5zlIKqOZ6Pgdxmi8TggeMSezH7vVB17OtT0IlpXdtN0MF9ipAlXa+oOflNUb/UwJ2qItoPUE/nmsaZhKymrogwKqr4aI6JdXA/AiFMJPg=
