language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker run -v $(pwd):/bin_destination devopspec/cli-installer
services:
- docker
script:
- bash ./dev-op-spec dev-ops run unit-test
- bash ./dev-op-spec dev-ops run publish
env:
  global:
  - secure: pJxji5YmpUEcpPOxkkEGN3HWCGEnNTI44Ex6JTlOFOAJ2zmX9SfwvKWO+r8iacq3o1mh/Kwj2EAUjr9XHOIiGADkqssvpDILnZM8QBWhnbc2blgSHlyA1JezWMZMO+761C1QUlw64AqMCQ+H4zJwTukisD1Kt397NgiSKCfiQzOaC832hOFCUe1QVmdaAlsYN5xo2zNLoSR6+lspBlTb8XncIfNElNh+7TBwzN+Z2CRW2DfJ8Q+6PCArijhaL28sIZAZZ84BkNe1Q0ig5k1Y8O4W3yxXhnZrTHiOZPIDVgjyiXb0IWjN8BpmnyLnCe5TvdjssGhkQCU5fr91LintCCVRmFpRguNNrRrfh7o//FKu6yzKN4AErKrXJ+CB+oT3+eEysHUiyQgwSoGfltA8xckunL+kiKjXUUNlRiyc1HL/CF/k91wqtI+c4QY3czzw9Ytpx40QJscoBiVgs4/Mzgq/wLLNkpKlDKO3lgdILzyJlkdEd85M9XdOQhczdG5J8nyHrF++qB+Yr7btFkpIuOS6CTJA6hpHiiKOxevu5h/MwnH9cO9zj5hQWnafIzaqLjtgQsj/bU8LQ3Ni3nlUt7RA1SH2f0lJk/yif2+TBYmXZs1ho3vmYvD7zmT/48gA2EUHwOF1e/OxOKGhPw0T7NsaAk9CwE7xT+6V4WoZeaM=
  - secure: A7T8PaWTWnoKsNVthH8ge/EGvfFate06qULrtcVk5lka2BY+zlrqTvs/KAv8s2U7FxS7WbYyBtwOgkz5EZmv7XBBV8l02RoaFTk8L7MiH5y3YLGX9WEfrayCk7MOYRJGyYTDKr9JOJDvwjFDhm7C+Lp2R7HoYkTjeqJdpxd//yszL+U+7sA+SBZmuPcroyPqnqzhjplwBZj45RUbiLoHXtTdsKl2pzbWzUwaq4M2/9hvuzYSrhYLiI8NoFYFiv5Qs0dwkCVtoEsFyGuWa/cmrWaRhqDjzKYx+umEZFxDnKfky/IO5lXRMiRLlIJ863ThJU4SXphP6sVB7D7cQ//RexrO99Cx3KNMRmg9buUNpYoXYEqY/S7wXGhHcr0pL31Q3A53CMGqyzGF0Xh7OfBKOHhjfn5+Vbndp8vRbLr0uHS1Wks3N3WJCusdXZ01hqKbQ0zE4STMQt+GlwaDHB5TijhZqaw2qE4aHNHpJQ/xt0QIRryiEN+15AHw0rKVC1RQPzLf4eXmWoF0DnX0rOfFR5yYi0KIk/4rlmKISPaMzNWdoqj0aHxoMhADb7fVi5+wlrHUcWtSR/9OEo6jCBk/3/b9xD68FRauK+sRtaPt5mGQxKOfTpB7iQoTgDbqZl6Kc/htZWxUW31MPljQMzepKlmwKyhhriPsXPp6p8Rh40A=
